// ═══════════════════════════════════════════════════════════════════════════
//  OwHAS — CENTRAL CONFIGURATION
//
//  This is the first file a new owner should read.
//  The most common customisation points are defined here as named constants
//  so that a single change propagates everywhere automatically.
//
//  For changes NOT controlled by this file, see the FILE MAP below.
// ═══════════════════════════════════════════════════════════════════════════
//
//  FILE MAP — where to find everything else
//  ─────────────────────────────────────────
//  App name shown on the phone home screen
//      → android/app/src/main/AndroidManifest.xml   (android:label)
//
//  App icon
//      → replace OHAS2.png at the project root, then run:
//        flutter pub run flutter_launcher_icons
//
//  App colours, fonts, card shapes, spacing
//      → lib/theme.dart
//        LightModeColors / DarkModeColors control the colour palette.
//        FontSizes controls text sizes.
//
//  Navigation routes (which screen maps to which URL)
//      → lib/nav.dart
//
//  Course catalogue (list of departments and subjects)
//      → lib/course_management.dart
//        CourseManagement.courses is the list that populates the picker.
//
//  Firebase project (authentication + cloud storage)
//      → lib/firebase_options.dart  (auto-generated by FlutterFire CLI)
//      → android/app/google-services.json
//
//  Android package name (com.example.attendance_app)
//      → android/app/build.gradle.kts  (applicationId)
//        Change this before publishing to the Play Store.
//
//  Server deployment mode (hotspot vs university VLAN)
//      → backend/server.js  top section  (SERVER_IP, PORT)
//
//  Server presence enforcement rules
//      → backend/server.js  top section  (HEARTBEAT_*, GEOFENCE_*, FACE_*)
//
//  Server auto-detection order (which IPs the app tries at startup)
//      → lib/services/server_config.dart   fixedCandidates list
//
// ═══════════════════════════════════════════════════════════════════════════

/// All runtime-tunable constants for the Flutter application.
///
/// Counterpart server constants live in the CONFIG block at the top of
/// backend/server.js and must be kept in sync manually.
class AppConfig {

  // ── App identity ───────────────────────────────────────────────────────────
  /// Shown in push notifications and the browser tab title.
  /// The home-screen label is set separately in AndroidManifest.xml.
  static const String appName = 'OwHAS';

  // ── Cloud server ───────────────────────────────────────────────────────────
  /// Primary HTTPS endpoint. Requires a reverse proxy (Nginx/Caddy) on the
  /// server machine that forwards port 443 → localhost:5501.
  /// Change this if you host the backend under your own domain.
  static const String cloudUrl = 'https://owhas.org';

  /// Direct HTTP fallback used when the reverse proxy is not configured.
  /// Format: http://<domain-or-ip>:<serverPort>
  /// Must match PORT in backend/server.js.
  static const String cloudUrlHttp = 'http://owhas.org:5501';

  /// Port the Node.js server listens on.
  /// Must match PORT in backend/server.js.
  /// Also update the hardcoded port numbers in lib/services/server_config.dart
  /// (fixedCandidates and subnetCandidates lists) if you change this.
  static const int serverPort = 5501;

  // ── Biometric face verification ────────────────────────────────────────────
  /// Cosine similarity threshold for the Flutter-side face duplicate check.
  ///
  /// Range: 0.0 (completely different faces) → 1.0 (pixel-perfect identical).
  /// Higher = stricter = harder to spoof with a similar face.
  /// Lower  = more lenient = reduces false rejections for twins or bad lighting.
  ///
  /// The server runs a complementary check using Euclidean distance
  /// (FACE_DISTANCE_THRESHOLD in backend/server.js). Both thresholds guard
  /// against proxy attendance — tune them together.
  static const double faceMatchThreshold = 0.82;

  // ── Lecturer dashboard ─────────────────────────────────────────────────────
  /// How often (seconds) the dashboard polls the server for attendance updates.
  /// Lower = more real-time display, slightly higher network usage.
  static const int dashboardRefreshSeconds = 5;

  // ── Session UI defaults ────────────────────────────────────────────────────
  /// Values pre-filled in the session creation form.
  /// The lecturer can override these per session before starting.
  /// The authoritative values that the server enforces come from the server
  /// (POST /api/session-config) — see backend/server.js DEFAULT_* constants.
  static const int defaultRequiredMinutes        = 15;
  static const int defaultGracePeriodMinutes     = 5;
  static const int defaultSessionDurationMinutes = 60;
}
